---
- name: Install NTP packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - tzdata

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Start and enable NTP service
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
