- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - parted

- name: Create partitions
  parted:
    device: "{{ item.device }}"
    number: "{{ item.partition }}"
    state: present
    part_type: "{{ item.type }}"
    part_start: "{{ item.start | default(omit) }}"
    part_end: "{{ item.end | default(omit) }}"
  with_items: "{{ block_devices }}"

- name: Create filesystems for partitions
  filesystem:
    fstype: "{{ item.filesystem }}"
    dev: "{{ item.device }}{{ item.partition }}"
  with_items: "{{ block_devices }}"

- name: Create mountpoints
  file:
    path: "{{ item.mountpoint }}"
    state: directory
  with_items: "{{ block_devices }}"

- name: Mount partitions
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.device }}{{ item.partition }}"
    fstype: "{{ item.filesystem }}"
    state: mounted
    boot: true
  with_items: "{{ block_devices }}"
