---
- name: Playbook for NAS hosts
  hosts: nas
  become: true
  become_method: su
  gather_facts: true
  roles:
    - common
    - ntp
    - mdadm
    - parted
    - samba
    - docker
    - nas

- name: Playbook for Vagrant
  hosts: nas-vagrant
  become: true
  become_method: sudo
  gather_facts: true
  roles:
    - common
    - ntp
    - mdadm
    - parted
    - samba
    - docker
    - nas
