---
ntp_daemon: ntp
ntp_area: europe
ntp_timezone: Europe/Vilnius
ntp_servers:
  - "0.{{ ntp_area }}.ntp.org"
  - "1.{{ ntp_area }}.ntp.org"
  - "2.{{ ntp_area }}.ntp.org"
  - "3.{{ ntp_area }}.ntp.org"
ntp_restrict:
  - "127.0.0.1"
  - "::1"
