---
- name: Configure NAS
  hosts: nas
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars/main.yml
  roles:
    - common
    - ntp
    - mdadm
    - parted
    - samba
    - docker
    - nas
