---
- name: Install locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Make sure locale is configured
  lineinfile:
    dest: /etc/default/locale
    state: present
    line: "{{ item }}"
  with_items:
    - 'LANG="en_US.UTF-8"'
    - 'LC_ALL="en_US.UTF-8"'
    - 'LANGUAGE="en_US:en"'
