- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - software-properties-common
    - dbus
    - git
    - sudo
    - whois
    - python
    - python-pip

- name: Upgrade the system
  apt:
    update_cache: yes
    upgrade: dist
