---
- name: Create users
  user:
    name: "{{ item.username }}"
    shell: "{{ item.shell | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    comment: "{{ item.name  | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
  no_log: true
  when: host_users is defined
  with_items: "{{ host_users }}"
