---
- name: Make sure old Docker versions are uninstalled
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Install requirements for apt https
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - docker-ce
    - python-pip

- name: Install Docker Python module
  pip:
    name: docker-py
    state: present

- name: Make sure Docker is started
  service:
    name: docker
    state: started
    enabled: true

- name: Add users to docker group
  user:
    name: "{{ item.username }}"
    group: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Create Docker storage
  file:
    path: "{{ docker_storage }}"
    mode: 0755
    state: directory

- name: Configure Docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
  register: docker_config
