---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - mdadm

- name: Create arrays
  shell: "yes | mdadm --create {{ item.device }} --level={{ item.level }} --name={{ item.name }} --raid-devices={{ item.members|count }} {{ item.members|join (' ') }} --metadata=1.00"
  with_items: "{{ array_devices }}"
  args:
    creates: "{{ item.device }}"

- name: Create filesystems for arrays
  filesystem:
    fstype: "{{ item.filesystem }}"
    dev: "{{ item.device }}"
  with_items: "{{ array_devices }}"

- name: Create mountpoints
  file:
    path: "{{ item.mountpoint }}"
    state: directory
  with_items: "{{ array_devices }}"

- name: Mount arrays
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: "{{ item.filesystem }}"
    state: mounted
    boot: true
  with_items: "{{ array_devices }}"

- name: Save RAID configuration
  shell: mdadm --detail --scan | tee -a /etc/mdadm/mdadm.conf
  changed_when: false

- name: Update initial RAM file system
  shell: update-initramfs -u
  changed_when: false
