---
- name: Create Jackett directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ jackett_watch_directory }}"
    - "{{ jackett_data_directory }}"
  when: jackett_enabled

- name: Create Jackett container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ jackett_watch_directory }}:/downloads:rw"
      - "{{ jackett_data_directory }}:/config:rw"
    ports:
      - "9117:9117"
    env:
      PUID: "{{ jackett_user_id }}"
      PGID: "{{ jackett_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
  when: jackett_enabled

- name: Remove Jackett container
  docker_container:
    name: jackett
    state: absent
  when: not jackett_enabled

- name: Remove Jackett directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ jackett_watch_directory }}"
    - "{{ jackett_data_directory }}"
  when: not jackett_enabled
