---
- name: Create Nginx directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx_log_directory }}"
    - "{{ nginx_data_directory }}"
    - "{{ nginx_data_directory }}/conf.d"
  when: nginx_enabled

- name: Create Nginx container
  docker_container:
    name: nginx
    image: nginx
    pull: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ nginx_data_directory }}/conf.d:/etc/nginx/conf.d:ro"
      - "{{ nginx_log_directory }}:/var/log/nginx:rw"
    restart_policy: unless-stopped
    memory: 1g
  when: nginx_enabled

- name: Create Nginx hosts
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_data_directory }}/conf.d/{{ item.name }}.conf"
  notify: restart nginx
  with_items: "{{ nginx_hosts }}"
  when:
    - (item.enabled or item.enabled == "1")
    - nginx_enabled

- name: Remove Nginx hosts
  file:
    path: "{{ nginx_data_directory }}/conf.d/{{ item.name }}.conf"
    state: absent
  with_items: "{{ nginx_hosts }}"
  notify: restart nginx
  when: not item.enabled or item.enabled == "0"

- name: Remove Nginx container
  docker_container:
    name: nginx
    state: absent
  when: not nginx_enabled

- name: Remove Nginx directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nginx_log_directory }}"
    - "{{ nginx_data_directory }}"
    - "{{ nginx_data_directory }}/conf.d"
  when: not nginx_enabled
