---
- name: Create Plex Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ plex_library_directory }}"
    - "{{ plex_transcode_directory }}"
    - "{{ plex_tv_directory }}"
    - "{{ plex_movies_directory }}"

- name: Plex Docker Container
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ plex_transcode_directory }}:/transcode:rw"
      - "{{ plex_library_directory }}:/config:rw"
      - "{{ plex_tv_directory }}:/data/tv:rw"
      - "{{ plex_movies_directory }}:/data/movies:rw"
    env:
      PUID: "{{ plex_user_id }}"
      PGID: "{{ plex_group_id }}"
      VERSION: "{{ plex_version }}"
    restart_policy: unless-stopped
    memory: 2g
