---
- name: Create Portainer directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ portainer_data_directory }}"
  when: portainer_enabled

- name: Create Portainer container
  docker_container:
    name: portainer
    image: portainer/portainer
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ portainer_data_directory }}:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "9000:9000"
    restart_policy: unless-stopped
    memory: 1g
  when: portainer_enabled

- name: Remove Portainer container
  docker_container:
    name: portainer
    state: absent
  when: not portainer_enabled

- name: Create Portainer Directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ portainer_data_directory }}"
  when: not portainer_enabled
