---
- name: Create Radarr directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ radarr_data_directory }}"
  when: radarr_enabled

- name: Create Radarr container
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ radarr_movies_directory }}:/movies:rw"
      - "{{ radarr_download_directory }}/complete:/downloads/complete:rw"
      - "{{ radarr_data_directory }}:/config:rw"
    ports:
      - "7878:7878"
    env:
      PUID: "{{ radarr_user_id }}"
      PGID: "{{ radarr_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
  when: radarr_enabled

- name: Remove Radarr container
  docker_container:
    name: radarr
    state: absent
  when: not radarr_enabled

- name: Remove Radarr directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ radarr_data_directory }}"
  when: not radarr_enabled
