---
- name: Create Time Machine directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ time_machine_directory }}"
  when: time_machine_enabled

- name: Create Time Machine container
  docker_container:
    name: timemachine
    image: odarriba/timemachine
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ time_machine_directory }}:/timemachine:rw"
    ports:
      - "548:548"
      - "636:636"
    env:
      AFP_LOGIN: "{{ time_machine_username }}"
      AFP_PASSWORD: "{{ time_machine_password }}"
      AFP_NAME: "{{ time_machine_volume_name }}"
      AFP_SIZE_LIMIT: "{{ time_machine_volume_size }}"
    restart_policy: unless-stopped
    memory: 1g
  when: time_machine_enabled

- name: Remove Time Machine container
  docker_container:
    name: timemachine
    state: absent
  when: not time_machine_enabled

- name: Remove Time Machine directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ time_machine_directory }}"
  when: not time_machine_enabled
