---
- name: Create Transmission directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ transmission_download_directory }}"
    - "{{ transmission_download_directory }}/complete"
    - "{{ transmission_download_directory }}/incomplete"
    - "{{ transmission_config_directory }}"
    - "{{ transmission_watch_directory }}"
  when: transmission_enabled or transmission_with_vpn_enabled

- name: Create Transmission container
  docker_container:
    name: transmission
    image: linuxserver/transmission
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ transmission_config_directory }}:/config:rw"
      - "{{ transmission_download_directory }}:/downloads:rw"
      - "{{ transmission_watch_directory }}:/watch:rw"
    ports:
      - "9091:9091"
      - "51414:51413"
    env:
      PUID: "{{ transmission_user_id }}"
      PGID: "{{ transmission_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
  when:
    - transmission_enabled
    - not transmission_with_vpn_enabled

- name: Create Transmission with VPN container
  docker_container:
    name: transmission-openvpn
    image: haugene/transmission-openvpn
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ transmission_config_directory }}:/config:rw"
      - "{{ transmission_download_directory }}:/downloads:rw"
      - "{{ transmission_watch_directory }}:/watch:rw"
    ports:
      - "9091:9091"
      - "51413:51413"
    env:
      TRANSMISSION_HOME: /config
      TRANSMISSION_DOWNLOAD_DIR: /downloads/complete
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_WATCH_DIR: /watch
      OPENVPN_PROVIDER: "{{ openvpn_provider }}"
      OPENVPN_USERNAME: "{{ openvpn_username }}"
      OPENVPN_PASSWORD: "{{ openvpn_password }}"
      OPENVPN_CONFIG: "{{ openvpn_config }}"
      PUID: "{{ transmission_user_id }}"
      PGID: "{{ transmission_group_id }}"
      LOCAL_NETWORK: "{{ transmission_local_network }}"
      ENABLE_UFW: false
    devices:
      - /dev/net/tun
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    memory: 1g
  when:
    - transmission_with_vpn_enabled
    - not transmission_enabled

- name: Remove Transmission container
  docker_container:
    name: transmission
    state: absent
  when: not transmission_enabled

- name: Remove Transmission with VPN container
  docker_container:
    name: transmission-openvpn
    state: absent
  when: not transmission_with_vpn_enabled

- name: Remove Transmission directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ transmission_download_directory }}"
    - "{{ transmission_download_directory }}/complete"
    - "{{ transmission_download_directory }}/incomplete"
    - "{{ transmission_config_directory }}"
    - "{{ transmission_watch_directory }}"
  when:
    - not transmission_enabled
    - not transmission_with_vpn_enabled
