---
# Enable or Disable Features
plex_enabled: true
sonarr_enabled: true
radarr_enabled: true
jackett_enabled: true
transmission_enabled: false
transmission_with_vpn_enabled: true
duplicati_enabled: true
glances_enabled: true
portainer_enabled: true
time_machine_enabled: true
nginx_enabled: true

# Users and Groups
nas_group: nas # Group name that will have access to all Samba shares

host_groups: # List of Linux groups to create
  - group: "{{ nas_group }}"

host_users: # List of Linux users to create
  - name: NAS
    username: nas
    password: "$6$3JXvyX2.9aLr$Wdp1MXdPC0mvZ0KLPC3lMbQzC6IaVHbtCqHZWGKLx9ezrujnJ7Q8JHjQL3lL98Wxu8oK93LXRemINr7aITPLl." # Ansible requires password to be encrypted: http://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
    samba_password: password # Samba needs password in plain text. Use Ansible Vault to store plain text password and encrypt the file.
    shell: /bin/bash
    groups: "{{ nas_group }},sudo"

# Hard Drives
array_devices: # List of RAID devices
  - name: array1
    device: /dev/md0
    members:
      - /dev/sdb
      - /dev/sdc
    filesystem: ext4
    level: 1
    mountpoint: /mnt/storage

block_devices: # List of single disk partitions
  - device: /dev/sdd
    partition: 1
    type: primary
    mountpoint: /mnt/backups
    filesystem: ext4
    start: 0%
    end: 100%

# Samba
samba_shares_root: /mnt/storage
samba_users: "{{ host_users }}"
samba_shares:
  - name: data
    comment: 'Data'
    group: "{{ nas_group }}"
    write_list: "+{{ nas_group }}"

  - name: media
    comment: 'Movies and TV Shows'
    group: "{{ nas_group }}"
    write_list: "+{{ nas_group }}"

  - name: downloads
    comment: 'Downloaded Stuff'
    group: "{{ nas_group }}"
    write_list: "+{{ nas_group }}"

# Docker
docker_storage: "{{ samba_shares_root }}/docker"
docker_users: "{{ host_users }}"

# Plex
plex_library_directory: "{{ docker_storage }}/plex/library"
plex_transcode_directory: "{{ docker_storage }}/plex/transcode"
plex_tv_directory: "{{ samba_shares_root }}/media/tv"
plex_movies_directory: "{{ samba_shares_root }}/media/movies"
plex_user_id: 0
plex_group_id: 0
plex_version: latest

# Sonarr
sonarr_data_directory: "{{ docker_storage }}/sonarr/config"
sonarr_tv_directory: "{{ samba_shares_root }}/media/tv"
sonarr_download_directory: "{{ samba_shares_root }}/downloads/complete"
sonarr_user_id: 0
sonarr_group_id: 0

# Radarr
radarr_data_directory: "{{ docker_storage }}/radarr/config"
radarr_movies_directory: "{{ samba_shares_root }}/media/movies"
radarr_download_directory: "{{ samba_shares_root }}/downloads/complete"
radarr_user_id: 0
radarr_group_id: 0

# Jackett
jackett_watch_directory: "{{ samba_shares_root }}/downloads/torrents"
jackett_data_directory: "{{ docker_storage }}/jackett/config"
jackett_user_id: 0
jackett_group_id: 0

# Transmission
transmission_config_directory: "{{ docker_storage }}/transmission/config"
transmission_download_directory: "{{ samba_shares_root }}/downloads"
transmission_watch_directory: "{{ samba_shares_root }}/downloads/torrents"
transmission_user_id: 0
transmission_group_id: 0
transmission_local_network: 192.168.0.0/24

# OpenVPN
openvpn_provider: NORDVPN
openvpn_config: lv6.nordvpn.com.udp.ovpn
openvpn_username: username
openvpn_password: password

# Duplicati
duplicati_data_directory: "{{ docker_storage }}/duplicati/config"

# Portainer
portainer_data_directory: "{{ docker_storage }}/portainer/config"

# Time Machine
time_machine_directory: "/mnt/backups/timemachine"
time_machine_volume_name: "TimeMachine"
time_machine_volume_size: 1000000
time_machine_username: nas
time_machine_password: password

# Nginx
nginx_data_directory: "{{ docker_storage }}/nginx/config"
nginx_log_directory: "{{ docker_storage }}/nginx/logs"
nginx_server: "{{ ansible_default_ipv4.address }}"
nginx_hosts:
  - name: plex
    port: 32400
    domains:
      - plex.nas
    enabled: "{{ plex_enabled }}"

  - name: radarr
    port: 7878
    domains:
      - radarr.nas
    enabled: "{{ radarr_enabled }}"

  - name: sonarr
    port: 8989
    domains:
      - sonarr.nas
    enabled: "{{ sonarr_enabled }}"

  - name: jackett
    port: 9117
    domains:
      - jackett.nas
    enabled: "{{ jackett_enabled }}"

  - name: transmission
    port: 9091
    domains:
      - transmission.nas
    enabled: "{{ transmission_enabled + transmission_with_vpn_enabled }}"

  - name: duplicati
    port: 8200
    domains:
      - duplicati.nas
    enabled: "{{ duplicati_enabled }}"

  - name: glances
    port: 61208
    domains:
      - glances.nas
    enabled: "{{ glances_enabled }}"

  - name: portainer
    port: 9000
    domains:
      - portainer.nas
    enabled: "{{ portainer_enabled }}"
